services:
  backend:
    container_name: aprovame_backend
    image: aprovame_backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      APP_PORT: 3000
      NODE_ENV: production
      DATABASE_URL: file:/app/database/preview.db
      JWT_SECRET: "789456123"
    volumes:
      - ./backend/database:/app/database
    networks:
      - aprovame-network

  frontend:
    container_name: app_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      NODE_ENV: production
    networks:
      - aprovame-network

networks:
  aprovame-network:
